// <auto-generated />
using System;
using Blogmanager_NguyenMinhQuan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace blogmanager_NguyenMinhQuan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806025723_AddCategoryValidation")]
    partial class AddCategoryValidation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("blogmanager_NguyenMinhQuan.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Công nghệ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lập trình"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Web Development"
                        });
                });

            modelBuilder.Entity("blogmanager_NguyenMinhQuan.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Nguyễn Trung",
                            Content = "Đây là bài viết đầu tiên.",
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Giới thiệu ASP.NET Core",
                            ViewCount = 120
                        },
                        new
                        {
                            Id = 2,
                            Author = "Nguyễn Minh Quân",
                            Content = "Làm quen với Migration.",
                            IsPublished = true,
                            PublishedAt = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Học Entity Framework Core",
                            ViewCount = 250
                        },
                        new
                        {
                            Id = 3,
                            Author = "Hồng Trung Việt",
                            Content = "Sử dụng Razor để hiển thị dữ liệu.",
                            IsPublished = false,
                            PublishedAt = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Razor View",
                            ViewCount = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
